# generated by configure / remove this line to disable regeneration
prefix="/s/chopin/b/grad/rohan94/Downloads/pocc-1.4/generators/install-cloog"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/s/chopin/b/grad/rohan94/Downloads/pocc-1.4/generators/cloog/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/s/chopin/b/grad/rohan94/Downloads/pocc-1.4/generators/cloog/./include"
package="cloog-isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "cloog-isl"
;; --help) pkg-config --help ; echo Buildscript Of "cloog-isl Library"
;; --modversion|--version) echo "0.18.2"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "-L/s/chopin/b/grad/rohan94/Downloads/pocc-1.4/math/external/install/lib" "-lcloog-isl -lgmp"
       :
;; --cflags) echo -I${includedir} "-I/s/chopin/b/grad/rohan94/Downloads/pocc-1.4/math/external/install/include -DCLOOG_INT_GMP=1"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
